/****** Object:  Table [AXSCONTROL].[ACCESS_USERS]    Script Date: 12/30/2014 09:55:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [AXSCONTROL].[ACCESS_USERS](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_INTERNAL_ID] [varchar](40) NOT NULL,
	[USER_LAST_NAME] [varchar](40) NOT NULL,
	[USER_FIRST_NAME] [varchar](40) NOT NULL,
	[USER_NAME_3] [varchar](40) NULL,
	[USER_NAME_4] [varchar](40) NULL,
	[USER_DOC_NUM] [varchar](50) NULL,
	[USER_ADDRESS1] [varchar](200) NULL,
	[USER_ADDRESS2] [varchar](200) NULL,
	[USER_PHONE1] [varchar](20) NULL,
	[USER_PHONE2] [varchar](20) NULL,
	[USER_EMAIL] [varchar](100) NULL,
	[USER_ADDRESS_GEOLOCATION] [geography] NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_USER_ID] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_USERS_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_USERS_AI]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_USERS_AI] ON [AXSCONTROL].[ACCESS_USERS]
AFTER INSERT
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_USERS]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_USERS].[USER_ID] = [INSERTED].[USER_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_USERS_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_USERS_AU]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_USERS_AU] ON [AXSCONTROL].[ACCESS_USERS]
AFTER UPDATE
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_USERS]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_USERS].[USER_ID] = [INSERTED].[USER_ID]
END
GO




/****** Object:  Table [AXSCONTROL].[ACCESS_TYPES]    Script Date: 12/30/2014 09:55:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [AXSCONTROL].[ACCESS_TYPES](
	[ACCCES_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACCESS_TYPE_NAME] [varchar](40) NOT NULL,
	[ACCESS_TYPE_STATUS] [int] NOT NULL DEFAULT 1,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
	[ACCESS_TYPE_TYPE] [INT] NOT NULL DEFAULT 1, 
 CONSTRAINT [PK_ACCESS_TYPES] PRIMARY KEY CLUSTERED 
(
	[ACCCES_TYPE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_ACCESS_TYPE_NAME] UNIQUE NONCLUSTERED 
(
	[ACCESS_TYPE_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_TYPES_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_TYPES_AI]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_TYPES_AI] ON [AXSCONTROL].[ACCESS_TYPES]
AFTER INSERT
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_TYPES]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_TYPES].[ACCESS_TYPE_ID] = [INSERTED].[ACCESS_TYPE_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_TYPES_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_TYPES_AU]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_TYPES_AU] ON [AXSCONTROL].[ACCESS_TYPES]
AFTER UPDATE
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_TYPES]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_TYPES].[ACCESS_TYPE_ID] = [INSERTED].[ACCESS_TYPE_ID]
END
GO




/****** Object:  Table [AXSCONTROL].[ACCESS_TYPE_VALUES]    Script Date: 12/30/2014 09:54:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [AXSCONTROL].[ACCESS_TYPE_VALUES](
	[ACCESS_TYPE_ID] [int] NOT NULL,
	[TYPE_VALUE_ID] [int] NOT NULL IDENTITY,
	[TYPE_VALUE_NAME] [varchar](100) NOT NULL,
	[TYPE_VALUE_DISPLAY] [varchar](100) NULL,
	[TYPE_VALUE_INT_VAL] [int] NULL,
	[TYPE_VALUE_CHAR_VAL] [varchar](200) NULL,
	[TYPE_VALUE_DEFAULT] [int] NOT NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_ACCESS_TYPE_VALUES] PRIMARY KEY CLUSTERED 
(
	[TYPE_VALUE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_ACCESS_TYPE_VALUE_NAME] UNIQUE NONCLUSTERED 
(
	[TYPE_VALUE_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [AXSCONTROL].[ACCESS_TYPE_VALUES]  WITH CHECK ADD  CONSTRAINT [FK_ACCESS_TYPE_VALUES_ACCESS_TYPES] FOREIGN KEY([ACCESS_TYPE_ID])
REFERENCES [AXSCONTROL].[ACCESS_TYPES] ([ACCCES_TYPE_ID])
GO

ALTER TABLE [AXSCONTROL].[ACCESS_TYPE_VALUES] CHECK CONSTRAINT [FK_ACCESS_TYPE_VALUES_ACCESS_TYPES]
GO

ALTER TABLE [AXSCONTROL].[ACCESS_TYPE_VALUES] ADD  CONSTRAINT [DF_ACCESS_TYPE_ITEMS_TYPE_ITEM_DEFAULT]  DEFAULT ((0)) FOR [TYPE_VALUE_DEFAULT]
GO


-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_TYPE_VALUES_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_TYPE_VALUES_AI]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_TYPE_VALUES_AI] ON [AXSCONTROL].[ACCESS_TYPE_VALUES]
AFTER INSERT
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_TYPE_VALUES]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_TYPE_VALUES].[TYPE_VALUE_ID] = [INSERTED].[TYPE_VALUE_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_TYPE_VALUES_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_TYPE_VALUES_AU]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_TYPE_VALUES_AU] ON [AXSCONTROL].[ACCESS_TYPE_VALUES]
AFTER UPDATE
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_TYPE_VALUES]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_TYPE_VALUES].[TYPE_VALUE_ID] = [INSERTED].[TYPE_VALUE_ID]
END
GO





/****** Object:  Table [AXSCONTROL].[RESOURCE_CATEGORIES]    Script Date: 12/30/2014 09:55:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [AXSCONTROL].[RESOURCE_CATEGORIES](
	[CATEGORY_ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORY_NAME] [varchar](50) NOT NULL,
	[CATEGORY_DESCRIPTION] [varchar](2000) NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_OBJECT_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[CATEGORY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_RESOURCE_CATEGORIES_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_RESOURCE_CATEGORIES_AI]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_RESOURCE_CATEGORIES_AI] ON [AXSCONTROL].[RESOURCE_CATEGORIES]
AFTER INSERT
AS
BEGIN
	UPDATE [AXSCONTROL].[RESOURCE_CATEGORIES]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[RESOURCE_CATEGORIES].[CATEGORY_ID] = [INSERTED].[CATEGORY_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_RESOURCE_CATEGORIES_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_RESOURCE_CATEGORIES_AU]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_RESOURCE_CATEGORIES_AU] ON [AXSCONTROL].[RESOURCE_CATEGORIES]
AFTER UPDATE
AS
BEGIN
	UPDATE [AXSCONTROL].[RESOURCE_CATEGORIES]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[RESOURCE_CATEGORIES].[CATEGORY_ID] = [INSERTED].[CATEGORY_ID]
END
GO




/****** Object:  Table [AXSCONTROL].[ACCESS_REQUESTS]    Script Date: 12/30/2014 09:54:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [AXSCONTROL].[ACCESS_REQUESTS](
	[REQUEST_ID] [int] IDENTITY(1,1) NOT NULL,
	[REQUEST_NUMBER] [int] NULL,
	[REQUEST_BY] [varchar](50) NOT NULL,
	[REQUEST_TO] [varchar](50) NOT NULL,
	[REQUEST_DATE] [datetime] NULL,
	[REQUEST_TYPE] [int] NOT NULL,
	[REQUEST_DEPARTMENT] [int] NOT NULL,
	[REQUEST_PRIORITY] [int] NOT NULL,
	[REQUEST_STATUS] [int] NULL,
	[REQUEST_COMPLETED_DATE] [datetime] NULL,
	[REQUEST_NOTE] [varchar](2000) NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [varchar](50) NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_ACCESS_REQUESTS] PRIMARY KEY CLUSTERED 
(
	[REQUEST_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [AXSCONTROL].[ACCESS_REQUESTS]  WITH CHECK ADD  CONSTRAINT [FK_ACCESS_REQUESTS_COMMON_VALUES_REQ_PRIORITY] FOREIGN KEY([REQUEST_PRIORITY])
REFERENCES [SITCORE].[COMMON_VALUES] ([COMMON_VALUE_ID])
GO

ALTER TABLE [AXSCONTROL].[ACCESS_REQUESTS] CHECK CONSTRAINT [FK_ACCESS_REQUESTS_COMMON_VALUES_REQ_PRIORITY]
GO

ALTER TABLE [AXSCONTROL].[ACCESS_REQUESTS]  WITH CHECK ADD  CONSTRAINT [FK_ACCESS_REQUESTS_COMMON_VALUES_REQ_STATUS] FOREIGN KEY([REQUEST_STATUS])
REFERENCES [SITCORE].[COMMON_VALUES] ([COMMON_VALUE_ID])
GO

ALTER TABLE [AXSCONTROL].[ACCESS_REQUESTS] CHECK CONSTRAINT [FK_ACCESS_REQUESTS_COMMON_VALUES_REQ_STATUS]
GO

ALTER TABLE [AXSCONTROL].[ACCESS_REQUESTS]  WITH CHECK ADD  CONSTRAINT [FK_ACCESS_REQUESTS_COMMON_VALUES_REQ_TYPE] FOREIGN KEY([REQUEST_TYPE])
REFERENCES [SITCORE].[COMMON_VALUES] ([COMMON_VALUE_ID])
GO

ALTER TABLE [AXSCONTROL].[ACCESS_REQUESTS] CHECK CONSTRAINT [FK_ACCESS_REQUESTS_COMMON_VALUES_REQ_TYPE]
GO


-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_REQUESTS_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_REQUESTS_AI]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_REQUESTS_AI] ON [AXSCONTROL].[ACCESS_REQUESTS]
AFTER INSERT
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_REQUESTS]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[REQUEST_NUMBER] = (SELECT COALESCE(MAX([REQUEST_NUMBER]), 0) + 1 FROM [AXSCONTROL].[ACCESS_REQUESTS]),
		[REQUEST_STATUS] = (SELECT [SITCORE].[COMMON_VALUES].[COMMON_VALUE_ID] FROM [SITCORE].[COMMON_VALUE_SETS]
							INNER JOIN [SITCORE].[COMMON_VALUES] ON([SITCORE].[COMMON_VALUE_SETS].[COMMON_VALUE_SET_ID] = [SITCORE].[COMMON_VALUES].[COMMON_VALUE_SET_ID])
							WHERE
							  [SITCORE].[COMMON_VALUE_SETS].[COMMON_VALUE_SET_NAME] = 'ESTADOS_SOLICITUD'
							  AND [SITCORE].[COMMON_VALUES].[COMMON_VALUE_NAME] = 'S_PENDIENTE'),
		[REQUEST_DATE] = CURRENT_TIMESTAMP,
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_REQUESTS].[REQUEST_ID] = [INSERTED].[REQUEST_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_REQUESTS_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_REQUESTS_AU]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_REQUESTS_AU] ON [AXSCONTROL].[ACCESS_REQUESTS]
AFTER UPDATE
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_REQUESTS]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_REQUESTS].[REQUEST_ID] = [INSERTED].[REQUEST_ID]
END
GO





/****** Object:  Table [AXSCONTROL].[ACCESS_RESOURCES]    Script Date: 12/30/2014 09:51:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [AXSCONTROL].[ACCESS_RESOURCES](
	[RESOURCE_ID] [int] IDENTITY(1,1) NOT NULL,
	[RESOURCE_CATEGORY] [int] NOT NULL,
	[RESOURCE_NAME] [varchar](100) NOT NULL,
	[RESOURCE_DESCRIPTION] [varchar](2000) NULL,
	[RESOURCE_PARENT] [int] NULL,
	[RESOURCE_PARAM1] [varchar](500) NULL,
	[RESOURCE_PARAM2] [varchar](500) NULL,
	[RESOURCE_PARAM3] [varchar](500) NULL,
	[RESOURCE_PARAM4] [varchar](500) NULL,
	[RESOURCE_PARAM5] [varchar](500) NULL,
	[RESOURCE_PARAM6] [varchar](500) NULL,
	[RESOURCE_PARAM7] [varchar](500) NULL,
	[RESOURCE_PARAM8] [varchar](500) NULL,
	[RESOURCE_PARAM9] [varchar](500) NULL,
	[RESOURCE_PARAM10] [varchar](500) NULL,
	[RESOURCE_ACCESS_TYPE] [int] NOT NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_ACCESS_RESOURCE] PRIMARY KEY CLUSTERED 
(
	[RESOURCE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [AXSCONTROL].[ACCESS_RESOURCES]  WITH CHECK ADD  CONSTRAINT [FK_ACCESS_RESOURCES_ACCESS_RESOURCES] FOREIGN KEY([RESOURCE_PARENT])
REFERENCES [AXSCONTROL].[ACCESS_RESOURCES] ([RESOURCE_ID])
GO

ALTER TABLE [AXSCONTROL].[ACCESS_RESOURCES] CHECK CONSTRAINT [FK_ACCESS_RESOURCES_ACCESS_RESOURCES]
GO

ALTER TABLE [AXSCONTROL].[ACCESS_RESOURCES]  WITH CHECK ADD  CONSTRAINT [FK_ACCESS_RESOURCES_ACCESS_TYPES] FOREIGN KEY([RESOURCE_ACCESS_TYPE])
REFERENCES [AXSCONTROL].[ACCESS_TYPES] ([ACCCES_TYPE_ID])
GO

ALTER TABLE [AXSCONTROL].[ACCESS_RESOURCES] CHECK CONSTRAINT [FK_ACCESS_RESOURCES_ACCESS_TYPES]
GO

ALTER TABLE [AXSCONTROL].[ACCESS_OBJECTS]  WITH CHECK ADD  CONSTRAINT [FK_ACCESS_RESOURCES_RESOURCE_CATEGORIES] FOREIGN KEY([RESOURCE_CATEGORY])
REFERENCES [AXSCONTROL].[RESOURCE_CATEGORIES] ([CATEGORY_ID])
GO

ALTER TABLE [AXSCONTROL].[ACCESS_RESOURCE] CHECK CONSTRAINT [FK_ACCESS_RESOURCES_RESOURCE_CATEGORIES]
GO


-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_RESOURCES_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_RESOURCES_AI]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_RESOURCES_AI] ON [AXSCONTROL].[ACCESS_RESOURCES]
AFTER INSERT
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_RESOURCES]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_RESOURCES].[RESOURCE_ID] = [INSERTED].[RESOURCE_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_RESOURCES_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_RESOURCES_AU]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_RESOURCES_AU] ON [AXSCONTROL].[ACCESS_RESOURCES]
AFTER UPDATE
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_RESOURCES]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_RESOURCES].[RESOURCE_ID] = [INSERTED].[RESOURCE_ID]
END
GO




/****** Object:  Table [AXSCONTROL].[USER_OBJECT_ACCESS]    Script Date: 12/30/2014 09:56:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [AXSCONTROL].[USER_OBJECT_ACCESS](
	[UO_ID] [int] NOT NULL,
	[UO_USER_ID] [int] NOT NULL,
	[UO_OBJECT_ID] [int] NOT NULL,
	[UO_ACCESS_VALUE] [int] NOT NULL,
	[UO_UP_DATE] [datetime] NOT NULL,
	[UO_UP_WORKFLOW] [int] NOT NULL,
	[UO_DOWN_DATE] [datetime] NULL,
	[UO_DOWN_WORKFLOW] [int] NULL,
	[UO_ACTIVE] [int] NOT NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_USER_OBJECT_ACCESS] PRIMARY KEY CLUSTERED 
(
	[UO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_USER_OBJECT_ACCESS_ACCESS_TYPE_VALUES] FOREIGN KEY([UO_ID])
REFERENCES [AXSCONTROL].[ACCESS_TYPE_VALUES] ([TYPE_VALUE_ID])
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS] CHECK CONSTRAINT [FK_USER_OBJECT_ACCESS_ACCESS_TYPE_VALUES]
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_USER_OBJECT_ACCESS_ACCESS_USERS] FOREIGN KEY([UO_USER_ID])
REFERENCES [AXSCONTROL].[ACCESS_USERS] ([USER_ID])
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS] CHECK CONSTRAINT [FK_USER_OBJECT_ACCESS_ACCESS_USERS]
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_USER_OBJECT_ACCESS_USER_OBJECT_ACCESS] FOREIGN KEY([UO_OBJECT_ID])
REFERENCES [AXSCONTROL].[ACCESS_OBJECTS] ([OBJECT_ID])
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS] CHECK CONSTRAINT [FK_USER_OBJECT_ACCESS_USER_OBJECT_ACCESS]
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_USER_OBJECT_ACCESS_WORKFLOW_EXECUTION_DOWN] FOREIGN KEY([UO_DOWN_WORKFLOW])
REFERENCES [SITWORKFLOW].[WORKFLOW_EXECUTION] ([WF_EXEC_ID])
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS] CHECK CONSTRAINT [FK_USER_OBJECT_ACCESS_WORKFLOW_EXECUTION_DOWN]
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_USER_OBJECT_ACCESS_WORKFLOW_EXECUTION_UP] FOREIGN KEY([UO_UP_WORKFLOW])
REFERENCES [SITWORKFLOW].[WORKFLOW_EXECUTION] ([WF_EXEC_ID])
GO

ALTER TABLE [AXSCONTROL].[USER_OBJECT_ACCESS] CHECK CONSTRAINT [FK_USER_OBJECT_ACCESS_WORKFLOW_EXECUTION_UP]
GO


-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_USER_OBJECT_ACCESS_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_USER_OBJECT_ACCESS_AI]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_USER_OBJECT_ACCESS_AI] ON [AXSCONTROL].[USER_OBJECT_ACCESS]
AFTER INSERT
AS
BEGIN
	UPDATE [AXSCONTROL].[USER_OBJECT_ACCESS]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[USER_OBJECT_ACCESS].[UO_ID] = [INSERTED].[UO_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_USER_OBJECT_ACCESS_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_USER_OBJECT_ACCESS_AU]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_USER_OBJECT_ACCESS_AU] ON [AXSCONTROL].[USER_OBJECT_ACCESS]
AFTER UPDATE
AS
BEGIN
	UPDATE [AXSCONTROL].[USER_OBJECT_ACCESS]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[USER_OBJECT_ACCESS].[UO_ID] = [INSERTED].[UO_ID]
END
GO















/****** Object:  Table [AXSCONTROL].[ACCESS_REQUEST_DETAILS]    Script Date: 12/30/2014 09:51:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [AXSCONTROL].[ACCESS_REQUEST_DETAILS](
	[REQUEST_ID] [int] NOT NULL,
	[REQUEST_DET_ID] [int] IDENTITY NOT NULL,
	[REQUEST_DET_RESOURCE_ID] [int] NOT NULL,
	[REQUEST_DET_STATUS] [int] NULL,
	[REQUEST_DET_STEP] [int] NOT NULL DEFAULT 1,
	[REQUEST_DET_TYPE] [int] NULL,
	[REQUEST_DET_STR_VALUE] [varchar](200) NULL,
	[REQUEST_DET_INT_VALUE] [int] NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_ACCESS_REQUEST_DETAIL] PRIMARY KEY CLUSTERED 
(
	[REQUEST_DET_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [AXSCONTROL].[ACCESS_REQUEST_DETAILS]  WITH CHECK ADD CONSTRAINT [FK_ACCESS_REQ_DET_ACCESS_REQUEST] FOREIGN KEY([REQUEST_ID])
REFERENCES [AXSCONTROL].[ACCESS_REQUESTS] ([REQUEST_ID])
GO
ALTER TABLE [AXSCONTROL].[ACCESS_REQUEST_DETAILS] CHECK CONSTRAINT [FK_ACCESS_REQ_DET_ACCESS_REQUEST]
GO

ALTER TABLE [AXSCONTROL].[ACCESS_REQUEST_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ACCESS_REQ_DET_ACCESS_RESOURCES] FOREIGN KEY([REQUEST_DET_RESOURCE_ID])
REFERENCES [AXSCONTROL].[ACCESS_RESOURCES] ([RESOURCE_ID])
GO
ALTER TABLE [AXSCONTROL].[ACCESS_REQUEST_DETAILS] CHECK CONSTRAINT [FK_ACCESS_REQ_DET_ACCESS_RESOURCES]
GO



-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_REQUEST_DETAILS_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_REQUEST_DETAILS_AI]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_REQUEST_DETAILS_AI] ON [AXSCONTROL].[ACCESS_REQUEST_DETAILS]
AFTER INSERT
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_REQUEST_DETAILS]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_REQUEST_DETAILS].[REQUEST_DET_ID] = [INSERTED].[REQUEST_DET_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_ACCESS_REQUEST_DETAILS_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [AXSCONTROL].[TRG_ACCESS_REQUEST_DETAILS_AU]
END
GO
CREATE TRIGGER [AXSCONTROL].[TRG_ACCESS_REQUEST_DETAILS_AU] ON [AXSCONTROL].[ACCESS_REQUEST_DETAILS]
AFTER UPDATE
AS
BEGIN
	UPDATE [AXSCONTROL].[ACCESS_REQUEST_DETAILS]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [AXSCONTROL].[ACCESS_REQUEST_DETAILS].[REQUEST_DET_ID] = [INSERTED].[REQUEST_DET_ID]
END
GO