/****** DROP TABLES FIRST IN ORDER   ****/

IF EXISTS (SELECT * 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_SCHEMA = 'PROJ' 
           AND  TABLE_NAME = 'PROJECTS'
		  )
BEGIN
	DROP TABLE [PROJ].[PROJECTS];
END;
GO


/****** Object:  Table [PROJ].[PROJECTS]    Script Date: 01/30/2015 09:55:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [PROJ].[PROJECTS](
	[PROJECT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROJECT_ORG_ID] [int] NOT NULL,
	[PROJECT_CODE] [varchar](40) NOT NULL,
	[PROJECT_NAME] [varchar](400) NOT NULL,
	[PROJECT_DESCRIPTION] [varchar](4000) NULL,
	[PROJECT_RESPONSIBLE1] [int] NULL,
	[PROJECT_RESPONSIBLE2] [int] NULL,
	[PROJECT_RESPONSIBLE3] [int] NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_PROJECT_ID] PRIMARY KEY CLUSTERED 
(
	[PROJECT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_PROJECT_CODE] UNIQUE NONCLUSTERED 
(
	[PROJECT_CODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_PROJECT_NAME] UNIQUE NONCLUSTERED 
(
	[PROJECT_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

