/****** DROP TABLES FIRST IN ORDER   ****/

IF EXISTS (SELECT * 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_SCHEMA = 'HHRR' 
           AND  TABLE_NAME = 'DEPARTMENT_POSITIONS'
		  )
BEGIN
	DROP TABLE [HHRR].[DEPARTMENT_POSITIONS];
END;
GO


IF EXISTS (SELECT * 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_SCHEMA = 'HHRR' 
           AND  TABLE_NAME = 'PEOPLE_DEPARTMENTS'
		  )
BEGIN
	DROP TABLE [HHRR].PEOPLE_DEPARTMENTS;
END;
GO


IF EXISTS (SELECT * 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_SCHEMA = 'HHRR' 
           AND  TABLE_NAME = 'PEOPLE'
		  )
BEGIN
	DROP TABLE [HHRR].[PEOPLE];
END;
GO

IF EXISTS (SELECT * 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_SCHEMA = 'HHRR' 
           AND  TABLE_NAME = 'DEPARTMENTS'
		  )
BEGIN
	DROP TABLE [HHRR].[DEPARTMENTS];
END;
GO

IF EXISTS (SELECT * 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_SCHEMA = 'HHRR' 
           AND  TABLE_NAME = 'ORGANIZATIONS'
		  )
BEGIN
	DROP TABLE [HHRR].[ORGANIZATIONS];
END;
GO


/****** Object:  Table [HHRR].[ORGANIZATIONS]    Script Date: 01/30/2015 09:55:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [HHRR].[ORGANIZATIONS](
	[ORG_ID] [int] IDENTITY(1,1) NOT NULL,
	[ORG_SHORT_NAME] [varchar](400) NOT NULL,
	[ORG_LEGAL_NAME] [varchar](400) NOT NULL,
	[ORG_LEGAL_NUM] [varchar](200) NOT NULL,
	[ORG_DISPLAY_TEXT] [varchar] (400) NULL,
	[ORG_IMAGE1_URL] [varchar] (400) NULL,
	[ORG_IMAGE2_URL] [varchar] (400) NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_ORG_ID] PRIMARY KEY CLUSTERED 
(
	[ORG_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_ORG_SHORT_NAME] UNIQUE NONCLUSTERED 
(
	[ORG_SHORT_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



/****** Object:  Table [HHRR].[PEOPLE]    Script Date: 01/30/2015 09:55:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [HHRR].[PEOPLE](
	[PEOPLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PEOPLE_ORG_ID] [int] NOT NULL,
	[PEOPLE_INTERNAL_ID] [varchar](40) NULL,
	[PEOPLE_LAST_NAME] [varchar](40) NOT NULL,
	[PEOPLE_FIRST_NAME] [varchar](40) NOT NULL,
	[PEOPLE_LAST_NAME2] [varchar](40) NULL,
	[PEOPLE_FIRST_NAME2] [varchar](40) NULL,
	[PEOPLE_DOC_TYPE] [int] NOT NULL,
	[PEOPLE_DOC_NUM] [varchar](50) NULL,
	[PEOPLE_ADDRESS1] [varchar](200) NULL,
	[PEOPLE_ADDRESS2] [varchar](200) NULL,
	[PEOPLE_PHONE1] [varchar](20) NULL,
	[PEOPLE_PHONE2] [varchar](20) NULL,
	[PEOPLE_EMAIL] [varchar](100) NULL,
	[PEOPLE_ADDRESS_GEOLOCATION] [geography] NULL,
	[PEOPLE_IMAGE] [varbinary](max) NULL,
	[PEOPLE_ATTRIBUTE1] [varchar](2000) NULL,
	[PEOPLE_ATTRIBUTE2] [varchar](2000) NULL,
	[PEOPLE_ATTRIBUTE3] [varchar](2000) NULL,
	[PEOPLE_ATTRIBUTE4] [varchar](2000) NULL,
	[PEOPLE_ATTRIBUTE5] [varchar](2000) NULL,
	[PEOPLE_ATTRIBUTE6] [varchar](2000) NULL,
	[PEOPLE_ATTRIBUTE7] [varchar](2000) NULL,
	[PEOPLE_ATTRIBUTE8] [varchar](2000) NULL,
	[PEOPLE_ATTRIBUTE9] [varchar](2000) NULL,
	[PEOPLE_ATTRIBUTE10] [varchar](2000) NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
	[PEOPLE_DEPARTMENT] INT NOT NULL, 
    [PEOPLE_POSITION] INT NOT NULL, 
 CONSTRAINT [PK_PEOPLE_ID] PRIMARY KEY CLUSTERED 
(
	[PEOPLE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_PEOPLE_INTERNAL_ID] UNIQUE NONCLUSTERED 
(
	[PEOPLE_ORG_ID],
	[PEOPLE_INTERNAL_ID]
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_PEOPLE_DOC_NUM] UNIQUE NONCLUSTERED 
(
	[PEOPLE_ORG_ID],
	[PEOPLE_DOC_TYPE],
	[PEOPLE_DOC_NUM]
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


ALTER TABLE [HHRR].[PEOPLE]  WITH CHECK ADD  CONSTRAINT [FK_PEOPLE_DOC_TYPE] FOREIGN KEY([PEOPLE_DOC_TYPE])
REFERENCES [SITCORE].[COMMON_VALUES] ([COMMON_VALUE_ID])
GO
ALTER TABLE [HHRR].[PEOPLE] CHECK CONSTRAINT [FK_PEOPLE_DOC_TYPE]
GO

ALTER TABLE [HHRR].[PEOPLE]  WITH CHECK ADD  CONSTRAINT [FK_PEOPLE_POSITION] FOREIGN KEY([PEOPLE_POSITION])
REFERENCES [SITCORE].[COMMON_VALUES] ([COMMON_VALUE_ID])
GO
ALTER TABLE [HHRR].[PEOPLE] CHECK CONSTRAINT [FK_PEOPLE_POSITION]
GO

ALTER TABLE [HHRR].[PEOPLE]  WITH CHECK ADD  CONSTRAINT [FK_PEOPLE_DEPARTMENT] FOREIGN KEY([PEOPLE_DEPARTMENT])
REFERENCES [SITCORE].[COMMON_VALUES] ([COMMON_VALUE_ID])
GO
ALTER TABLE [HHRR].[PEOPLE] CHECK CONSTRAINT [FK_PEOPLE_DEPARTMENT]
GO



/****** Object:  Table [HHRR].[DEPARTMENTS]    Script Date: 01/30/2015 09:55:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [HHRR].[DEPARTMENTS](
	[DEPARTMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[DEPARTMENT_ORG_ID] [varchar](40) NULL,
	[DEPARTMENT_CODE] [varchar](40) NULL,
	[DEPARTMENT_NAME] [varchar](240) NULL,
	[DEPARTMENT_PARENT] [int] NULL,
	[DEPARTMENT_STATUS] [varchar](40) NULL,
	[DEPARTMENT_OBSERVATION] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE1] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE2] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE3] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE4] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE5] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE6] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE7] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE8] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE9] [varchar](2000) NULL,
	[DEPARTMENT_ATTRIBUTE10] [varchar](2000) NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_DEPARTMENT_ID] PRIMARY KEY CLUSTERED 
(
	[DEPARTMENT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_DEPARTMENT_CODE] UNIQUE NONCLUSTERED 
(
	[DEPARTMENT_ORG_ID],
	[DEPARTMENT_CODE]

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_DEPARTMENT_NAME] UNIQUE NONCLUSTERED 
(
	[DEPARTMENT_ORG_ID],
	[DEPARTMENT_NAME]
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



/****** Object:  Table [HHRR].[PEOPLE_DEPARTMENTS]    Script Date: 01/30/2015 09:55:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [HHRR].[PEOPLE_DEPARTMENTS](
	[PEOPLE_ID] [int] NOT NULL,
	[DEPARTMENT_ID] [int] NOT NULL,
	[PD_STATUS] [int] NOT NULL,
	[PD_START_DATE] [datetime] NOT NULL,
	[PD_END_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_PEOPLE_DEPARTMENT] PRIMARY KEY CLUSTERED 
(
	[PEOPLE_ID],
	[DEPARTMENT_ID]
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [HHRR].[PEOPLE_DEPARTMENTS]  ADD  CONSTRAINT [FK_PD_PEOPLE_ID] FOREIGN KEY([PEOPLE_ID])
	REFERENCES [HHRR].[PEOPLE]([PEOPLE_ID])
GO
ALTER TABLE [HHRR].[PEOPLE_DEPARTMENTS]  ADD  CONSTRAINT [FK_PD_DEPARTMENT_ID] FOREIGN KEY([DEPARTMENT_ID])
	REFERENCES [HHRR].[DEPARTMENTS]([DEPARTMENT_ID])

GO

SET ANSI_PADDING OFF
GO


/****** Object:  Table [HHRR].[[DEPARTMENT_POSITIONS]]    Script Date: 01/30/2015 09:55:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [HHRR].[DEPARTMENT_POSITIONS](	
	[POSITION_ID] [int] IDENTITY(1,1) NOT NULL,
	[DEPARTMENT_ID] [int] NOT NULL,
	[POSITION_NAME] [varchar](400) NOT NULL,
	[POSITION_PARENT] [int] NULL,
	[PEOPLE_ID] [int] NULL,
	[POSITION_STATUS] [int] NOT NULL,
	[POSITION_START_DATE] [datetime] NOT NULL,
	[POSITION_END_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_DEPARTMENT_POSITIONS] PRIMARY KEY CLUSTERED 
(
	[POSITION_ID]
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [HHRR].[DEPARTMENT_POSITIONS]  ADD  CONSTRAINT [FK_POSITION_DEPARTMENT_ID] FOREIGN KEY([DEPARTMENT_ID])
	REFERENCES [HHRR].[DEPARTMENTS]([DEPARTMENT_ID])
GO
ALTER TABLE [HHRR].[DEPARTMENT_POSITIONS]  ADD  CONSTRAINT [FK_POSITION_PEOPLE_ID] FOREIGN KEY([PEOPLE_ID])
	REFERENCES [HHRR].[PEOPLE]([PEOPLE_ID])
GO



SET ANSI_PADDING OFF
GO
