/****** Object:  Table [SITCORE].[COMMON_VALUE_SETS]    Script Date: 12/30/2014 09:57:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SITCORE].[COMMON_VALUE_SETS](
	[COMMON_VALUE_SET_ID] [int] IDENTITY(1,1) NOT NULL,
	[COMMON_VALUE_SET_NAME] [varchar](150) NOT NULL,
	[COMMON_VALUE_SET_DESC] [varchar](2000) NULL,
	[COMMON_VALUE_SET_SEQ_SEED] [int] NOT NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
	[COMMON_VALUE_SET_SYSTEM_VALUE] [INT] NOT NULL DEFAULT 0, 
 CONSTRAINT [PK_COMMON_VALUE_SETS] PRIMARY KEY CLUSTERED 
(
	[COMMON_VALUE_SET_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_COMMON_VALUE_SETS] UNIQUE NONCLUSTERED 
(
	[COMMON_VALUE_SET_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_COMMON_VALUE_SETS_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITCORE].[TRG_COMMON_VALUE_SETS_AI]
END
GO

CREATE TRIGGER [SITCORE].[TRG_COMMON_VALUE_SETS_AI] ON [SITCORE].[COMMON_VALUE_SETS]
AFTER INSERT
AS
BEGIN
	UPDATE [SITCORE].[COMMON_VALUE_SETS]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITCORE].[COMMON_VALUE_SETS].[COMMON_VALUE_SET_ID] = [INSERTED].[COMMON_VALUE_SET_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_COMMON_VALUE_SETS_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITCORE].[TRG_COMMON_VALUE_SETS_AU]
END
GO
CREATE TRIGGER [SITCORE].[TRG_COMMON_VALUE_SETS_AU] ON [SITCORE].[COMMON_VALUE_SETS]
AFTER UPDATE
AS
BEGIN
	UPDATE [SITCORE].[COMMON_VALUE_SETS]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITCORE].[COMMON_VALUE_SETS].[COMMON_VALUE_SET_ID] = [INSERTED].[COMMON_VALUE_SET_ID]
END
GO




/****** Object:  Table [SITCORE].[COMMON_VALUES]    Script Date: 12/30/2014 09:58:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SITCORE].[COMMON_VALUES](
	[COMMON_VALUE_ID] [int] IDENTITY(1,1) NOT NULL,
	[COMMON_VALUE_SET_ID] [int] NOT NULL,
	[COMMON_VALUE_NAME] [varchar](150) NOT NULL,
	[COMMON_VALUE_DISPLAY] [varchar](150) NOT NULL,
	[COMMON_VALUE_DESC] [varchar](500) NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_COMMON_VALUES] PRIMARY KEY CLUSTERED 
(
	[COMMON_VALUE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_COMMON_VALUES] UNIQUE NONCLUSTERED 
(
	[COMMON_VALUE_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SITCORE].[COMMON_VALUES]  WITH CHECK ADD  CONSTRAINT [FK_COMMON_VALUES_COMMON_VALUE_SETS] FOREIGN KEY([COMMON_VALUE_SET_ID])
REFERENCES [SITCORE].[COMMON_VALUE_SETS] ([COMMON_VALUE_SET_ID])
GO

-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_COMMON_VALUES_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITCORE].[TRG_COMMON_VALUES_AI]
END
GO

CREATE TRIGGER [SITCORE].[TRG_COMMON_VALUES_AI] ON [SITCORE].[COMMON_VALUES]
AFTER INSERT
AS
BEGIN
	UPDATE [SITCORE].[COMMON_VALUES]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITCORE].[COMMON_VALUES].[COMMON_VALUE_ID] = [INSERTED].[COMMON_VALUE_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_COMMON_VALUES_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITCORE].[TRG_COMMON_VALUES_AU]
END
GO
CREATE TRIGGER [SITCORE].[TRG_COMMON_VALUES_AU] ON [SITCORE].[COMMON_VALUES]
AFTER UPDATE
AS
BEGIN
	UPDATE [SITCORE].[COMMON_VALUES]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITCORE].[COMMON_VALUES].[COMMON_VALUE_ID] = [INSERTED].[COMMON_VALUE_ID]
END
GO


/****** Object:  Table [SITCORE].[SYSTEM_CONFIG]    Script Date: 04/02/2015 09:57:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SITCORE].[SYSTEM_CONFIG](
	[SYSCONF_ID] [int] IDENTITY(1,1) NOT NULL,
	[SYSCONF_NAME] [varchar](150) NOT NULL,
	[SYSCONF_DESC] [varchar](2000) NULL,
	[SYSCONF_VALUE1] [varchar](2000) NULL,
	[SYSCONF_VALUE2] [varchar](2000) NULL,
	[SYSCONF_VALUE3] [varchar](2000) NULL,
	[SYSCONF_VALUE4] [varchar](2000) NULL,
	[SYSCONF_VALUE5] [varchar](2000) NULL,
	[SYSCONF_VALUE6] [varchar](2000) NULL,
	[SYSCONF_VALUE7] [varchar](2000) NULL,
	[SYSCONF_VALUE8] [varchar](2000) NULL,
	[SYSCONF_VALUE9] [varchar](2000) NULL,
	[SYSCONF_VALUE10] [varchar](2000) NULL,
	[SYSCONF_VALUE11] [varchar](2000) NULL,
	[SYSCONF_VALUE12] [varchar](2000) NULL,
	[SYSCONF_VALUE13] [varchar](2000) NULL,
	[SYSCONF_VALUE14] [varchar](2000) NULL,
	[SYSCONF_VALUE15] [varchar](2000) NULL,
	[SYSCONF_VALUE16] [varchar](2000) NULL,
	[SYSCONF_VALUE17] [varchar](2000) NULL,
	[SYSCONF_VALUE18] [varchar](2000) NULL,
	[SYSCONF_VALUE19] [varchar](2000) NULL,
	[SYSCONF_VALUE20] [varchar](2000) NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_SYSTEM_CONFIG] PRIMARY KEY CLUSTERED 
(
	[SYSCONF_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_SYSCONF_NAME] UNIQUE NONCLUSTERED 
(
	[SYSCONF_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_SYSTEM_CONFIG_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITCORE].[TRG_SYSTEM_CONFIG_AI]
END
GO

CREATE TRIGGER [SITCORE].[TRG_SYSTEM_CONFIG_AI] ON [SITCORE].[SYSTEM_CONFIG]
AFTER INSERT
AS
BEGIN
	UPDATE [SITCORE].[SYSTEM_CONFIG]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITCORE].[SYSTEM_CONFIG].[SYSCONF_ID] = [INSERTED].[SYSCONF_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_SYSTEM_CONFIG_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITCORE].[TRG_SYSTEM_CONFIG_AU]
END
GO
CREATE TRIGGER [SITCORE].[TRG_SYSTEM_CONFIG_AU] ON [SITCORE].[SYSTEM_CONFIG]
AFTER UPDATE
AS
BEGIN
	UPDATE [SITCORE].[SYSTEM_CONFIG]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITCORE].[SYSTEM_CONFIG].[SYSCONF_ID] = [INSERTED].[SYSCONF_ID]
END
GO



