IF EXISTS (SELECT * 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_SCHEMA = 'SITWF' 
           AND  TABLE_NAME = 'WORKFLOW_HIERARCHY_MEMBERS'
		  )
BEGIN
	DROP TABLE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS];
END;
GO

IF EXISTS (SELECT * 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_SCHEMA = 'SITWF' 
           AND  TABLE_NAME = 'WORKFLOW_APPROVE_HIERARCHY'
		  )
BEGIN
	DROP TABLE [SITWF].[WORKFLOW_APPROVE_HIERARCHY];
END;
GO








/****** Object:  Table [SITWF].[WORKFLOW_APPROVE_HIERARCHY]    Script Date: 12/30/2014 10:00:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [SITWF].[WORKFLOW_APPROVE_HIERARCHY] (
    [WF_HIERARCHY_ID]   INT          NOT NULL,
    [WF_HIERARCHY_NAME] VARCHAR (200) NOT NULL,
    [CREATE_USER]       VARCHAR (50)  NULL,
    [CREATE_DATE]       DATETIME      NULL,
    [EDIT_USER]         VARCHAR (50)  NOT NULL,
    [EDIT_DATE]         DATETIME      NULL,
    CONSTRAINT [PK_WORKFLOW_APPROVE_HIERARCHY] PRIMARY KEY CLUSTERED ([WF_HIERARCHY_ID])
);
GO


SET ANSI_PADDING OFF
GO

-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOW_HIERARCHY_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOW_HIERARCHY_AI]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOW_HIERARCHY_AI] ON [SITWF].[WORKFLOW_APPROVE_HIERARCHY]
AFTER INSERT
AS
BEGIN
	UPDATE [SITWF].[WORKFLOW_APPROVE_HIERARCHY]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOW_APPROVE_HIERARCHY].[WF_HIERARCHY_ID] = [INSERTED].[WF_HIERARCHY_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOW_HIERARCHY_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOW_HIERARCHY_AU]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOW_HIERARCHY_AU] ON [SITWF].[WORKFLOW_APPROVE_HIERARCHY]
AFTER UPDATE
AS
BEGIN
	UPDATE [SITWF].[WORKFLOW_APPROVE_HIERARCHY]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOW_APPROVE_HIERARCHY].[WF_HIERARCHY_ID] = [INSERTED].[WF_HIERARCHY_ID]
END
GO









/****** Object:  Table [SITWF].[WORKFLOW_HIERARCHY_MEMBERS]    Script Date: 12/30/2014 10:00:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS] (
    [WF_HIERARCHY_MEMBER_ID]          INT NOT NULL IDENTITY,
	[WF_HIERARCHY_ID]                 INT NOT NULL,
	[WF_HIERARCHY_MEMBER_DEPARTMENT]  INT NOT NULL,
	[WF_HIERARCHY_MEMBER_POSITION]    INT NOT NULL,
	[WF_HIERARCHY_MEMBER_ORDER]       INT NOT NULL,
    [WF_HIERARCHY_MEMBER_DESCRIPTION] VARCHAR (200) NULL,
    [CREATE_USER]       VARCHAR (50)  NULL,
    [CREATE_DATE]       DATETIME      NULL,
    [EDIT_USER]         VARCHAR (50)  NOT NULL,
    [EDIT_DATE]         DATETIME      NULL,
    CONSTRAINT [PK_WORKFLOW_HIERARCHY_MEMBERS] PRIMARY KEY CLUSTERED ([WF_HIERARCHY_MEMBER_ID])
);
GO


SET ANSI_PADDING OFF
GO


ALTER TABLE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS]  WITH CHECK ADD  CONSTRAINT [FK_WF_HIERARCHY_MEMBERS_WF_APPROVE_HIERARCHY] FOREIGN KEY([WF_HIERARCHY_ID])
REFERENCES [SITWF].[WORKFLOW_APPROVE_HIERARCHY] ([WF_HIERARCHY_ID])
GO
ALTER TABLE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS] CHECK CONSTRAINT [FK_WF_HIERARCHY_MEMBERS_WF_APPROVE_HIERARCHY]
GO

ALTER TABLE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS]  WITH CHECK ADD  CONSTRAINT [FK_WF_HIERARCHY_MEMBERS_DEPARTMENT] FOREIGN KEY([WF_HIERARCHY_MEMBER_DEPARTMENT])
REFERENCES [SITCORE].[COMMON_VALUES] ([COMMON_VALUE_ID])
GO
ALTER TABLE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS] CHECK CONSTRAINT [FK_WF_HIERARCHY_MEMBERS_DEPARTMENT]
GO

ALTER TABLE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS]  WITH CHECK ADD  CONSTRAINT [FK_WF_HIERARCHY_MEMBERS_POSITION] FOREIGN KEY([WF_HIERARCHY_MEMBER_POSITION])
REFERENCES [SITCORE].[COMMON_VALUES] ([COMMON_VALUE_ID])
GO
ALTER TABLE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS] CHECK CONSTRAINT [FK_WF_HIERARCHY_MEMBERS_POSITION]
GO



-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOW_HIERARCHY_MEMBERS_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOW_HIERARCHY_MEMBERS_AI]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOW_HIERARCHY_MEMBERS_AI] ON [SITWF].[WORKFLOW_HIERARCHY_MEMBERS]
AFTER INSERT
AS
BEGIN
	UPDATE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOW_HIERARCHY_MEMBERS].[WF_HIERARCHY_MEMBER_ID] = [INSERTED].[WF_HIERARCHY_MEMBER_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOW_HIERARCHY_MEMBERS_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOW_HIERARCHY_MEMBERS_AU]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOW_HIERARCHY_MEMBERS_AU] ON [SITWF].[WORKFLOW_HIERARCHY_MEMBERS]
AFTER UPDATE
AS
BEGIN
	UPDATE [SITWF].[WORKFLOW_HIERARCHY_MEMBERS]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOW_HIERARCHY_MEMBERS].[WF_HIERARCHY_MEMBER_ID] = [INSERTED].[WF_HIERARCHY_MEMBER_ID]
END
GO











/****** Object:  Table [SITWF].[WORKFLOWS]    Script Date: 12/30/2014 09:59:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SITWF].[WORKFLOWS](
	[WF_ID] [int] IDENTITY(1,1) NOT NULL,
	[WF_HIERARCHY_ID] [int] NOT NULL,
	[WF_NAME] [varchar](200) NOT NULL,
	[WF_DESCRIPTION] [varchar](2000) NULL,
	[WF_START_DATE] [date] NOT NULL,
	[WF_END_DATE] [date] NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_WORKFLOWS] PRIMARY KEY CLUSTERED 
(
	[WF_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ_WORKFLOW_NAME] UNIQUE NONCLUSTERED 
(
	[WF_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SITWF].[WORKFLOWS]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_WORKFLOW_APPROVE_HIERARCHY] FOREIGN KEY([WF_HIERARCHY_ID])
REFERENCES [SITWF].[WORKFLOW_APPROVE_HIERARCHY] ([WF_HIERARCHY_ID])
GO

ALTER TABLE [SITWF].[WORKFLOWS] CHECK CONSTRAINT [FK_WORKFLOW_WORKFLOW_APPROVE_HIERARCHY]
GO


-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOWS_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOWS_AI]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOWS_AI] ON [SITWF].[WORKFLOWS]
AFTER INSERT
AS
BEGIN
	UPDATE [SITWF].[WORKFLOWS]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOWS].[WF_ID] = [INSERTED].[WF_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOWS_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOWS_AU]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOWS_AU] ON [SITWF].[WORKFLOWS]
AFTER UPDATE
AS
BEGIN
	UPDATE [SITWF].[WORKFLOWS]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOWS].[WF_ID] = [INSERTED].[WF_ID]
END
GO




/****** Object:  Table [SITWF].[WORKFLOW_ITEMS]    Script Date: 12/30/2014 09:59:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SITWF].[WORKFLOW_ITEMS](
	[WF_ITEM_ID] [int] NOT NULL,
	[WF_ITEM_WF_ID] [int] NOT NULL,
	[WF_ITEM_NAME] [varchar](200) NOT NULL,
	[WF_ITEM_TYPE] [int] NOT NULL,
	[WF_ITEM_SUBJECT] [VARCHAR] (2000) NULL,
	[WF_ITEM_MESSAGE] [text] NOT NULL,
	[WF_ITEM_STEP] [int] NOT NULL,
	[WF_ITEM_ENTER_CONDITION] [varchar](50) NULL,
	[WF_ITEM_ENTER_PARAMS] [varchar](2000) NULL,
	[WF_ITEM_PREV_SIBLING] [int] NULL,
	[WF_ITEM_EXIT_VALUES] [varchar](50) NULL,
	[WF_ITEM_DEST_TYPE] [INT] NULL,
	[WF_ITEM_DEST_MAIL] [VARCHAR] (2000) NULL,
	[WF_ITEM_NEXT_ITEM] [INT] NULL,
	[WF_ITEM_APPROVE_ITEM] [INT] NULL,
	[WF_ITEM_REJECT_ITEM] [INT] NULL,
	[WF_ITEM_TIMEOUT_ITEM] [INT] NULL,
	[WF_ITEM_TIMEOUT_DUE_TIME] [INT] NULL,
	[WF_ITEM_TIMEOUT_DUE_UNITS] [INT] NULL,
	[WF_ITEM_ACTION_PROPERTY] [INT] NULL,
	[WF_ITEM_ACTION_VALUE] [INT] NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_WORKFLOW_ITEMS] PRIMARY KEY CLUSTERED 
(
	[WF_ITEM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SITWF].[WORKFLOW_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_ITEMS_WORKFLOWS] FOREIGN KEY([WF_ITEM_WF_ID])
REFERENCES [SITWF].[WORKFLOWS] ([WF_ID])
GO

ALTER TABLE [SITWF].[WORKFLOW_ITEMS] CHECK CONSTRAINT [FK_WORKFLOW_ITEMS_WORKFLOWS]
GO


-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOW_ITEMS_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOW_ITEMS_AI]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOW_ITEMS_AI] ON [SITWF].[WORKFLOW_ITEMS]
AFTER INSERT
AS
BEGIN
	UPDATE [SITWF].[WORKFLOW_ITEMS]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOW_ITEMS].[WF_ITEM_ID] = [INSERTED].[WF_ITEM_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOW_ITEMS_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOW_ITEMS_AU]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOW_ITEMS_AU] ON [SITWF].[WORKFLOW_ITEMS]
AFTER UPDATE
AS
BEGIN
	UPDATE [SITWF].[WORKFLOW_ITEMS]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOW_ITEMS].[WF_ITEM_ID] = [INSERTED].[WF_ITEM_ID]
END
GO




/****** Object:  Table [SITWF].[WORKFLOW_EXECUTION]    Script Date: 12/30/2014 10:00:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SITWF].[WORKFLOW_EXECUTION](
	[WF_EXEC_ID] [int] NOT NULL,
	[WF_EXEC_START_DATE] [datetime] NOT NULL,
	[WF_EXEC_WF_ID] [int] NOT NULL,
	[WF_EXEC_STARTED_BY] [int] NOT NULL,
	[WF_EXEC_CURRENT_ITEM] [int] NOT NULL,
	[CREATE_USER] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[EDIT_USER] [varchar](50) NOT NULL,
	[EDIT_DATE] [datetime] NULL,
 CONSTRAINT [PK_WORKFLOWF_EXEC] PRIMARY KEY CLUSTERED 
(
	[WF_EXEC_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SITWF].[WORKFLOW_EXECUTION]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_EXECUTION_WORKFLOW_EXECUTION] FOREIGN KEY([WF_EXEC_WF_ID])
REFERENCES [SITWF].[WORKFLOWS] ([WF_ID])
GO

ALTER TABLE [SITWF].[WORKFLOW_EXECUTION] CHECK CONSTRAINT [FK_WORKFLOW_EXECUTION_WORKFLOW_EXECUTION]
GO

ALTER TABLE [SITWF].[WORKFLOW_EXECUTION]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_EXECUTION_WORKFLOW_ITEMS] FOREIGN KEY([WF_EXEC_CURRENT_ITEM])
REFERENCES [SITWF].[WORKFLOW_ITEMS] ([WF_ITEM_ID])
GO

ALTER TABLE [SITWF].[WORKFLOW_EXECUTION] CHECK CONSTRAINT [FK_WORKFLOW_EXECUTION_WORKFLOW_ITEMS]
GO


-- trigger AFTER INSERT
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOW_EXECUTION_AI' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOW_EXECUTION_AI]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOW_EXECUTIONS_AI] ON [SITWF].[WORKFLOW_EXECUTION]
AFTER INSERT
AS
BEGIN
	UPDATE [SITWF].[WORKFLOW_EXECUTION]
	SET
		[CREATE_USER] = [INSERTED].[EDIT_USER],
		[CREATE_DATE] = CURRENT_TIMESTAMP,
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOW_EXECUTION].[WF_EXEC_ID] = [INSERTED].[WF_EXEC_ID]
END
GO

-- trigger AFTER UPDATE
IF EXISTS(select * from dbo.sysobjects where name = 'TRG_WORKFLOW_EXECUTION_AU' and OBJECTPROPERTY(id, 'IsTrigger') = 1)
BEGIN
	DROP TRIGGER [SITWF].[TRG_WORKFLOW_EXECUTION_AU]
END
GO
CREATE TRIGGER [SITWF].[TRG_WORKFLOW_EXECUTION_AU] ON [SITWF].[WORKFLOW_EXECUTION]
AFTER UPDATE
AS
BEGIN
	UPDATE [SITWF].[WORKFLOW_EXECUTION]
	SET
		[EDIT_DATE] = CURRENT_TIMESTAMP
	FROM [INSERTED]
	WHERE
	  [SITWF].[WORKFLOW_EXECUTION].[WF_EXEC_ID] = [INSERTED].[WF_EXEC_ID]
END
GO



